Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyCartMVC.Models;
using Newtonsoft.Json;
using System.Text;

namespace MyCartMVC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly DeliveryManagementSystemContext dd;
        private readonly ISession session;

        public CustomerController(DeliveryManagementSystemContext _dd, IHttpContextAccessor httpContextAccessor)
        {
            dd= _dd;
            session = httpContextAccessor.HttpContext.Session;

        }
        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(CustomerRegistration e)
        {
            using (var client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");
                using (var response = await client.PostAsync("https://localhost:44374/api/Customer/AddRegistration", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    var empobj = JsonConvert.DeserializeObject<CustomerRegistration>(apiresponse);
                }
            }
            return RedirectToAction("Login");
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public  IActionResult Login(CustomerRegistration e)
        {
            // HttpContext.Session.SetString("Uno", dd.CustomerRegistrations);
            using (var client = new HttpClient())
            {
             using (var response = client.GetAsync("https://localhost:44374/api/Customer/AddLogin?username="+e.CustomerName+"&password="+e.Password).Result)
                {
                    string apiresponse = response.Content.ReadAsStringAsync().Result;
                  //string json = JsonConvert.SerializeObject(apiresponse, Formatting.Indented);
                    var empobj = JsonConvert.DeserializeObject<CustomerRegistration>(apiresponse);
                    if (empobj!=null)
                    {
                        ViewBag.SuccessMessage="You have logged in successfully!!!";
                        HttpContext.Session.SetInt32("cusid", empobj.CustomerId);
                        HttpContext.Session.SetString("Cname", empobj.CustomerName);
                        return RedirectToAction("Home");
                    }
                    else
                    {
                        ViewBag.FailureMessage="Invalid UserName or Password";
                        return View();

                    }
                }
               
            }
            

        }
        public IActionResult RegLogPage()
        {
            return View();
        }
        
        public IActionResult Home()
        {
            return View();
        }
    
        [HttpGet]
        public IActionResult AddBooking()
        {
            var Cname = HttpContext.Session.GetString("cname");
            if(Cname !=null)
            {
                return RedirectToAction("Home");

            }
            else
            {
                return View("Login");
            }
          //  return View();
        }
        


        [HttpPost]
          public IActionResult AddBooking(AddBooking a)
        {
            // var Myid= HttpContext.Session.GetString("cusid");
            // a.CustomerId=int.Parse(Myid);
           
            var Eid=HttpContext.Session.GetInt32("Empid");
            var cusid=HttpContext.Session.GetInt32("cusid");
            a.CustomerId=cusid;
            a.ExecutiveId=Eid;
            // ViewBag.vval=a.CustomerId;
            dd.AddBookings.Add(a);
            dd.SaveChanges();
            return View("success");
            List<int> exe = (from i in dd.ExecutiveRegistrations
                      select i.ExecutiveId).ToList();
            //var final = dd.AddBookings.Where(val=>val.CustomerId==a.CustomerId).ToList();
            //return View("viewBooking", final);

             }
        public IActionResult success()
        {
            return View();
        }
        public IActionResult ViewBooking()
        {
            var ans= HttpContext.Session.GetInt32("cusid");
          
            var result = dd.AddBookings.Where(res => res.CustomerId==ans).ToList();

            return View("ViewBooking",result);

        }
       
        //public IActionResult Delete()
        //{
        //    var del= HttpContext.Session.GetInt32("cusid");
        //    return View();
        //}


        public IActionResult DeleteBooking()

        {
            // var remove=  HttpContext.Session.GetString(id.ToString());
            var del = HttpContext.Session.GetInt32("cusid");
            var e = dd.AddBookings.ToList();
            var res = dd.AddBookings.Where(var => var.CustomerId==del);
            return View(res);
        }
        
        
        public IActionResult DeleteConfirmed(int id)
        {
           // var del = HttpContext.Session.GetInt32("cusid");
            AddBooking e = dd.AddBookings.Find(id);
            dd.AddBookings.Remove(e);
            dd.SaveChanges();
            return View("DeleteSuccess");
            ////return RedirectToAction("ViewBooking");

        }
        public IActionResult DeleteSuccess()
        {

            return View();
        }
        //public IActionResult DeleteBooking(int OrderId)

        //{

        //    var result = dd.AddBookings.Where(res => res.CustomerId==ans);
        //    AddBooking e = dd.AddBookings.Find(OrderId);
        //     return View("DeleteBooking", e);

        //}
        //[HttpPost]
        //[ActionName("DeleteBooking")]

        //public IActionResult DeleteConfirmed(int OrderId)
        //{
        //  var sss=  HttpContext.Session.GetInt32("Orderid");
        //    var result = dd.AddBookings.Where(res => res.OrderId==sss);
        //    return View("DeleteBooking", result);



        //}
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }


    }
}

Controllers/ExecutiveController.cs
using Microsoft.AspNetCore.Mvc;
using MyCartMVC.Models;
using Newtonsoft.Json;
using System.Text;
using System;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Security.Cryptography.X509Certificates;
using Microsoft.EntityFrameworkCore;

namespace MyCartMVC.Controllers
{
    public class ExecutiveController : Controller
    {
        private readonly DeliveryManagementSystemContext dd;
        private readonly ISession session;
        public ExecutiveController(DeliveryManagementSystemContext _dd, IHttpContextAccessor httpContextAccessor)
        {
            dd= _dd;
            session = httpContextAccessor.HttpContext.Session;
        }
        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(ExecutiveRegistration e)
        {
            using (var client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");
                using (var response = await client.PostAsync("https://localhost:44374/api/Executive/AddRegistration", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    var empobj = JsonConvert.DeserializeObject<ExecutiveRegistration>(apiresponse);
                }
            }
            return RedirectToAction("Login");
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(ExecutiveRegistration e)
        {
            using (var client = new HttpClient())
            {
               // StringContent content = new StringContent(JsonConvert.SerializeObject(e), Encoding.UTF8, "application/json");
                using (var response =  client.GetAsync("https://localhost:44374/api/Executive/AddLogin?username="+e.ExecutiveName+"&password="+e.Password).Result)
                {
                    string apiresponse =  response.Content.ReadAsStringAsync().Result;
                    var empobj = JsonConvert.DeserializeObject<ExecutiveRegistration>(apiresponse);
                    if (empobj!=null)
                    {
                        HttpContext.Session.SetInt32("Empid", empobj.ExecutiveId);
                        HttpContext.Session.SetString("Ename", empobj.ExecutiveName);
                        return RedirectToAction("Home");
                    }
                    else
                    {
                        ViewBag.FailureMessage="Invalid UserName or Password";
                        return View();
                    }
                }
                
            }
         }
        public IActionResult Reglogpage()
        {
            return View();
        }
        public IActionResult Home()
        {
            if (HttpContext.Session.GetString("Ename")!=null) {
                return RedirectToAction("Home");

            }
            else
            {
                return View("Login");
            }
           
        }
       
        //public IActionResult Home()
        //{
        //    var emp = HttpContext.Session.GetInt32("Empid");
        //    var result = dd.AddBookings.Where(val => val.ExecutiveId==emp).ToList();
        //    if (result!=null) {
        //        return RedirectToAction("ViewRequest",result);
        //    }
        //    else
        //    {
        //        ViewBag.mess="no data";
        //        return View();
        //    }
        //}
        public IActionResult ViewRequest()
        {
           

           // var result = dd.AddBookings.ToList();

            var final = dd.AddBookings.Where(var => var.ExecutiveId==null).ToList();          
            return View("ViewRequest", final);



        }
        public IActionResult UpdateExecutive(int id)
        {
            var emp = HttpContext.Session.GetInt32("Empid");
            var fil = dd.AddBookings.Where(var => var.OrderId==id).FirstOrDefault();
            fil.ExecutiveId=emp;
            dd.AddBookings.Update(fil);
            dd.SaveChanges();
            return View("UpdateExecutive",new List<AddBooking> { fil});
        }
        public IActionResult BookDetails()
        {
            var empt = HttpContext.Session.GetInt32("Empid");
            var answer = dd.AddBookings.Where(var => var.ExecutiveId==empt).ToList();
                return View("UpdateExecutive",answer);
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }
    }
    }




 

Views/Shared/PartialExe.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<ul class="navbar-nav">
    @{
        ViewBag.Name = @HttpContextAccessor.HttpContext.Session.GetString("Ename");
    }
    @if (ViewBag.Name!=null)
    {
        <li class="nav-item">
            <a class="nav-link btn btn-link text-dark" href="#">Welcome @ViewBag.Name!!</a>
        </li>

      
      
       <li>
            @*<form id="logoutForm" class="form-inline" asp-controller="Login"  asp-action="Logout" asp-route-returnUrl="@Url.Action("Login", "Login", new { area = "" })">*@
            <form>
                <button id="delete" type="submit" style="background-color:white;padding:0 10px 0 10px" class="nav-link btn btn-link text-dark" asp-controller="Executive" asp-action="ViewRequest">ViewRequest</button>
            </form>
            @*</form>*@
      </li>
      <li>
            @*<form id="logoutForm" class="form-inline" asp-controller="Login"  asp-action="Logout" asp-route-returnUrl="@Url.Action("Login", "Login", new { area = "" })">*@
            <form>
                <button id="Booking" type="submit" style="background-color:white;padding:0 10px 0 10px" class="nav-link btn btn-link text-dark" asp-controller="Executive" asp-action="BookDetails">BookDetails</button>
            </form>
            @*</form>*@
        </li>
        
      <li>
            @*<form id="logoutForm" class="form-inline" asp-controller="Login"  asp-action="Logout" asp-route-returnUrl="@Url.Action("Login", "Login", new { area = "" })">*@
            <form>
                <button id="GotoHome" type="submit" style="background-color:white;padding:0 10px 0 10px" class="nav-link btn btn-link text-dark" asp-controller="Executive" asp-action="Home">Go to Home</button>
            </form>
            @*</form>*@
        </li>
      
        <li class="nav-item">
            @*<form id="logoutForm" class="form-inline" asp-controller="Login"  asp-action="Logout" asp-route-returnUrl="@Url.Action("Login", "Login", new { area = "" })">*@
            <form>
                <button id="logout" type="submit" style="background-color:white;padding:0 10px 0 10px" class="nav-link btn btn-link text-dark" asp-controller="Executive" asp-action="Logout">Logout</button>
            </form>
            @*</form>*@
        </li>
        
    }
    else
    {
    @*<li class="nav-item">
    <a class="nav-link text-dark" id="register" asp-controller="Executive" asp-action="Registration">Register</a>

    </li>
    <li class="nav-item">
    <a class="nav-link text-dark" id="login" asp-controller="Executive" asp-action="Login">Login</a>
    </li>*@
    }
</ul>

 

Views/Shared/PartialLayout.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@ 
@{
}
<ul class="navbar-nav">
    @{
        ViewBag.Data = @HttpContextAccessor.HttpContext.Session.GetString("Cname");
    }
    @if (ViewBag.Data!=null)
    {
        <li class="nav-item">
            <a class="nav-link btn btn-link text-dark" href="#">Welcome @ViewBag.Data!!</a>
        </li>
        
        <li class="nav-item">
            @*<form id="logoutForm" class="form-inline" asp-controller="Login"  asp-action="Logout" asp-route-returnUrl="@Url.Action("Login", "Login", new { area = "" })">*@
            <form>
                <button id="Add"  style="background-color:white" type="submit" class="nav-link btn btn-link text-dark" asp-controller="Customer" asp-action="AddBooking">AddBooking</button>
            </form>
            @*</form>*@ 
        </li>
        <li class="nav-item">
            @*<form id="logoutForm" class="form-inline" asp-controller="Login"  asp-action="Logout" asp-route-returnUrl="@Url.Action("Login", "Login", new { area = "" })">*@
            <form>
                <button id="view" style="background-color:white" type="submit" class="nav-link btn btn-link text-dark" asp-controller="Customer" asp-action="ViewBooking">ViewBooking</button>
            </form>
            @*</form>*@
        </li>
        
        <li class="nav-item">
            @*<form id="logoutForm" class="form-inline" asp-controller="Login"  asp-action="Logout" asp-route-returnUrl="@Url.Action("Login", "Login", new { area = "" })">*@
            <form>
                <button id="delete" style="background-color:white" type="submit" class="nav-link btn btn-link text-dark" asp-controller="Customer" asp-action="DeleteBooking">CancelBooking</button>
            </form>
            @*</form>*@
        </li>
        <li class="nav-item">
            @*<form id="logoutForm" class="form-inline" asp-controller="Login"  asp-action="Logout" asp-route-returnUrl="@Url.Action("Login", "Login", new { area = "" })">*@
            <form>
                <button id="gotohome" type="submit" style="background-color:white" type="submit" class="nav-link btn btn-link text-dark" asp-controller="Customer" asp-action="Home">Go to Home</button>
            </form>
            @*</form>*@
        </li>
        <li class="nav-item">
            @*<form id="logoutForm" class="form-inline" asp-controller="Login"  asp-action="Logout" asp-route-returnUrl="@Url.Action("Login", "Login", new { area = "" })">*@
            <form>
                <button id="logout" type="submit" style="background-color:white" type="submit" class="nav-link btn btn-link text-dark" asp-controller="Customer" asp-action="Logout">Logout</button>
            </form>
            @*</form>*@
        </li>
        
    }
    else
    {


      @* <li class="nav-item">
            <a class="nav-link text-dark" id="login" asp-controller="Customer" asp-action="Registration">Register</a>
        </li>
       
        <li class="nav-item">
            <a class="nav-link text-dark" id="login" asp-controller="Customer" asp-action="Login">Login</a>
        </li>*@
    }
    </ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        nav.navbar.navbar-custom{
            background:#167ac6 !important;
        }
    </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCartMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyCartMVC.styles.css" asp-append-version="true" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  bg-black  border-bottom box-shadow mb-3">
            <img src="~/images/MyCart-1 (5).png" height="7%" width="7%" style="display:flex;padding:5px;padding-left:20px" />
            <div class="container-fluid">
               @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyCart</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                      
                    </ul>
                </div>
                <partial name="PartialLayout" />
                <partial name="PartialExe"/>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyCartMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>